<a href="https://colab.research.google.com/github/nitishast/TF/blob/master/NLP_Text_Generation_using_Keras_and_TF2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 2.x

In [0]:
import numpy as np
import pandas as pd
import matplotlib as mp
import tensorflow as tf

In [8]:
tf.__version__

'2.1.0'

In [0]:
%tensorflow_version 2.x

In [0]:
path_to_file = "shakespeare.txt"

In [0]:
text = open(path_to_file,'r').read()

In [12]:
text[2999:30100]

"ne,\n  Beauty o'er-snowed and bareness every where:\n  Then were not summer's distillation left\n  A liquid prisoner pent in walls of glass,\n  Beauty's effect with beauty were bereft,\n  Nor it nor no remembrance what it was.\n    But flowers distilled though they with winter meet,\n    Leese but their show, their substance still lives sweet.\n\n\n                     6  \n  Then let not winter's ragged hand deface,\n  In thee thy summer ere thou be distilled:\n  Make sweet some vial; treasure thou some place,\n  With beauty's treasure ere it be self-killed:\n  That use is not forbidden usury,\n  Which happies those that pay the willing loan;\n  That's for thy self to breed another thee,\n  Or ten times happier be it ten for one,\n  Ten times thy self were happier than thou art,\n  If ten of thine ten times refigured thee:\n  Then what could death do if thou shouldst depart,\n  Leaving thee living in posterity?\n    Be not self-willed for thou art much too fair,\n    To be death's co

In [13]:
sorted(set(text)) # Return all the unique characters in the text file in a sorted manner. 

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [0]:
vocab = sorted(set(text)) #contains all the characters in the text  

In [15]:
len(vocab) # count the number of characters in the text file. This will be used at the output layer of the RNN

84

In [16]:
for pair in enumerate(vocab):
  print (pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [0]:
char_to_ind = {char:ind for ind,char in enumerate(vocab)}

In [0]:
ind_to_char = np.array(vocab)

In [19]:
ind_to_char[80]

'y'

In [0]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [21]:
encoded_text[:3]

array([0, 1, 1])

In [22]:
text[2:200]

"                    1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n "

In [23]:
encoded_text[2:200]

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64, 73, 60,
       74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,  1, 59,
       60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,  0,  1,
        1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57, 60, 56,
       76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63, 75,  1,
       69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76, 75,  1,
       56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63, 70, 76,
       67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60, 56, 74,
       60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,  1, 63,
       60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1, 63, 64,
       74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1])

### Defining the sequence length from the lines. To find the structure of the sentence.

In [24]:
print (text[:300])



                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fue


In [0]:
line = "From fairest creatures we desire increase" #Taking a single line 
lines = '''
From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease
'''

In [26]:
print (len(line))
print (len (lines))
# Here a structured line from the poem or suanet here is of 133 line hence taking it to be of 120 line. 
#This can change for different type of texts. A story or an email can have different sequence legnth

41
132


In [0]:
seq_len = 120

In [28]:
total_num_sep = print (len(text)// seq_len + 1)  # Finding the total sequences in the text. Also using + 1 as 0 is the indexing. 

45381


In [0]:
char_dateset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [30]:
type(char_dateset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [31]:
print (char_dateset)

<TensorSliceDataset shapes: (), types: tf.int64>


In [32]:
for item in char_dateset.take(500):
  print(ind_to_char[item.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


In [0]:
sequences = char_dateset.batch(batch_size=seq_len+1,drop_remainder=True)
#creating a sequence batches of length 121 from the dataset. Dropping the remaining characters from the text

In [0]:
#Now, creating a target sequences from sequence above by shifting each batch by +1 and storing in tuple object.

In [0]:
def create_seq_targets(seq):
  input_txt = seq[:-1] # "Hello my nam..."
  output_txt = seq[1:] # "ello my name...."
  return input_txt,output_txt

In [0]:
dataset = sequences.map(create_seq_targets)

In [37]:
for input_txt, target_txt in dataset.take(1):
  print(input_txt.numpy())
  print ("".join(ind_to_char[input_txt.numpy()])) ### This is the input sequence 
  print ('\n')
  print (target_txt.numpy())
  print ("".join(ind_to_char[target_txt.numpy()])) # This is the target sequence 
  print ('\n')

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 




### Next target is to create or generate the Training sequence. 
Batches and shuffle. 

In [0]:
# 
batch_size = 128

# Need to define the buffer size for also for randomamising. Else all the text in the memory can be randsomised.
buffer_size = 10000
dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)


In [39]:
type(dataset)

tensorflow.python.data.ops.dataset_ops.BatchDataset

In [0]:
vocab_size = len(vocab)
rnn_neurons=1026
embeded_dim=64

In [0]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [0]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true,y_pred,from_logits=True)


In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,GRU,Dense

In [0]:
def create_model(vocab_size,embeded_dim,rnn_neurons,batch_size):
  
  model = Sequential()
  model.add(Embedding(vocab_size,embeded_dim,batch_input_shape=[batch_size,None]))
  model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,
              recurrent_initializer='glorot_uniform'))

  model.add(Dense(vocab_size))

  model.compile('adam',loss=sparse_cat_loss)

  return model

In [0]:
model = create_model(vocab_size=vocab_size,embeded_dim=embeded_dim,rnn_neurons=rnn_neurons,
                     batch_size=batch_size)

In [46]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (128, None, 64)           5376      
_________________________________________________________________
gru (GRU)                    (128, None, 1026)         3361176   
_________________________________________________________________
dense (Dense)                (128, None, 84)           86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


# Train the model

In [0]:
for input_example_batch, target_example_batch in dataset.take(1):
  #input_example_batch is the first sequence of letters
  #target_example_batch is ths initial sequence shifted just one  
  example_batch_predections = model(input_example_batch)
  #print (tf.shape(input_example_batch))

In [48]:
example_batch_predections.shape

TensorShape([128, 120, 84])

In [49]:
example_batch_predections[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[ 2.0521251e-03, -1.7755585e-03,  2.6054389e-03, ...,
        -2.5667967e-03,  1.2200433e-03,  2.8477554e-04],
       [-3.6186865e-03, -3.5389732e-03,  3.9515942e-03, ...,
        -2.2552307e-03,  2.6777254e-03, -4.6404093e-03],
       [ 1.1694422e-03,  1.6424228e-03,  1.4082689e-03, ...,
         6.2749642e-03,  3.1601158e-03,  5.4023024e-03],
       ...,
       [-5.6377337e-03, -2.0983333e-03,  4.1400217e-03, ...,
         2.9928416e-03,  1.5711214e-03, -6.0065882e-04],
       [-9.9164899e-04, -9.2885401e-03,  4.6205269e-03, ...,
        -4.6009896e-05, -1.8227848e-03,  2.6598664e-03],
       [-2.4708356e-03, -4.1519394e-03,  7.8212107e-03, ...,
         7.4694334e-03, -2.3135873e-03,  3.3908251e-03]], dtype=float32)>

## Grabbing the indices from the tensor and finding the sequence of number generated by the predictor.

In [0]:

sample_indices = tf.random.categorical(example_batch_predections[0],num_samples=1)


## Next with the shape of this tensor, we need to convert it to an array to check out the char by passing in ind_to_char array.

In [0]:
sample_indices = tf.squeeze(sample_indices,axis =-1).numpy()
## reshaping into a numpy array by using squeeze method

In [52]:
sample_indices

array([37, 20, 32, 24, 57, 55,  7, 24, 80, 72, 15, 81, 25, 23, 30, 45, 53,
        9, 65, 55, 19, 82, 42, 34, 83, 35, 11, 41, 78, 34, 60, 49, 14,  0,
        0, 50, 19, 13, 80, 31, 67, 83, 51, 12,  0,  7, 78, 45, 25,  4, 74,
       29, 41, 42, 52, 58, 62, 19, 79,  3, 70, 58, 44, 77,  8, 74, 34, 19,
       73, 49, 40, 79,  2, 70, 70, 48, 54, 74, 26, 13, 45,  0, 22, 50, 80,
       81, 28, 48, 26, 64, 22, 34, 27, 24, 29, 33, 25, 76, 63, 15, 44, 68,
       14, 58, 63, 66, 57, 77, 11, 24, 79,  7, 74, 43,  8, 48, 65, 51, 80,
       18])

In [53]:
ind_to_char[sample_indices]

array(['L', '9', 'G', '>', 'b', '`', ')', '>', 'y', 'q', '4', 'z', '?',
       '<', 'E', 'T', ']', '-', 'j', '`', '8', '|', 'Q', 'I', '}', 'J',
       '0', 'P', 'w', 'I', 'e', 'X', '3', '\n', '\n', 'Y', '8', '2', 'y',
       'F', 'l', '}', 'Z', '1', '\n', ')', 'w', 'T', '?', '&', 's', 'D',
       'P', 'Q', '[', 'c', 'g', '8', 'x', '"', 'o', 'c', 'S', 'v', ',',
       's', 'I', '8', 'r', 'X', 'O', 'x', '!', 'o', 'o', 'W', '_', 's',
       'A', '2', 'T', '\n', ';', 'Y', 'y', 'z', 'C', 'W', 'A', 'i', ';',
       'I', 'B', '>', 'D', 'H', '?', 'u', 'h', '4', 'S', 'm', '3', 'c',
       'h', 'k', 'b', 'v', '0', '>', 'x', ')', 's', 'R', ',', 'W', 'j',
       'Z', 'y', '7'], dtype='<U1')

In [0]:
# Directory where the checkpoints will be saved
checkpoint_dir = './training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_prefix,save_weights_only=True)

In [0]:
## NEw code

import os 
checkpoint_path = "training_1\cp.ckpt" 

checkpoint_dir = os.path.dirname(checkpoint_path)

 # Create checkpoint  callback 
checkpoint_callback =tf.keras.callbacks.ModelCheckpoint(checkpoint_path,save_weights_only=True,verbose=1)

In [0]:
epochs = 1

In [64]:
model.fit(dataset,epochs=epochs)

Train for 351 steps
351/351 [==============================] - 44s 125ms/step - loss: 1.7372


In [0]:
#model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)
model = create_model(vocab_size=vocab_size,embeded_dim=embeded_dim,rnn_neurons=rnn_neurons,
                     batch_size=batch_size)

In [73]:
model.load_weights(model)



AttributeError: ignored

In [71]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (128, None, 64)           5376      
_________________________________________________________________
gru_3 (GRU)                  (128, None, 1026)         3361176   
_________________________________________________________________
dense_3 (Dense)              (128, None, 84)           86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [0]:
def generate_text(model,start_seed,gen_size=500,temp=1.0):
  '''
  model: Trained Model to Generate Text
  start_seed: Intial Seed text in string form
  gen_size: Number of characters to generate

  Basic idea behind this function is to take in some seed text, format it so
  that it is in the correct shape for our network, then loop the sequence as
  we keep adding our own predicted characters.
  '''

  # defining the number of elements we want to predict
  num_generate = gen_size
  # converting the charater in starting seed string into characters.
  input_eval = [char_to_ind[s] for s in start_seed]
  
  #changing the dimentsion so that its in right shape for our model.'
  input_eval = tf.expand_dims(input_eval,0)

  #empty list to append the text generated by the model
  text_generated = []

  #Need to set the temperature for the randomness in our model.
  #The temeprerature divdes the logits which will be used for the softmax function before passing onto the next
  temperature = temp

  #Resetting the state of model before calling calling the predection clears the hidden layer states.
  model.reset_states()

  #Looping in through each of the characters
  for i in range(num_generate): 

    prediction = model(input_eval)

    #squezzing to undo the expanding dimensions domne above.
    prediction = tf.squeeze(prediction,0)

    #dividing the logits
    prediction = prediction/temperature

    #finding the single digit from the tensor to find the index and pass ot character array to find the real letters.
    #use function random.categorical

    predicted_id = tf.random.categorical(prediction,num_samples=1)[-1:0].numpy()

    #Expand the predected text 
    input_eval = tf.expand_dims(predicted_id,0)

    #append into the list
    text_generated.append(ind_to_char[predicted_id])

  return (start_seed + "".join(text_generated))

In [0]:
print(generate_text(model,"BRUTU",gen_size=500))

In [0]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
  '''
  model: Trained Model to Generate Text
  start_seed: Intial Seed text in string form
  gen_size: Number of characters to generate

  Basic idea behind this function is to take in some seed text, format it so
  that it is in the correct shape for our network, then loop the sequence as
  we keep adding our own predicted characters. Similar to our work in the RNN
  time series problems.
  '''

  # Number of characters to generate
  num_generate = gen_size

  # Vecotrizing starting seed text
  input_eval = [char_to_ind[s] for s in start_seed]

  # Expand to match batch format shape
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty list to hold resulting generated text
  text_generated = []

  # Temperature effects randomness in our resulting text
  # The term is derived from entropy/thermodynamics.
  # The temperature is used to effect probability of next characters.
  # Higher probability == lesss surprising/ more expected
  # Lower temperature == more surprising / less expected
 
  temperature = temp

  # Here batch size == 1
  model.reset_states()

  for i in range(num_generate):

      # Generate Predictions
      print (tf.shape(input_eval))
      predictions = model(input_eval)

      # Remove the batch shape dimension
      predictions = tf.squeeze(predictions, 0)

      # Use a cateogircal disitribution to select the next character
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # Pass the predicted charracter for the next input
      input_eval = tf.expand_dims([predicted_id], 0)

      # Transform back to character letter
      text_generated.append(ind_to_char[predicted_id])

  return (start_seed + ''.join(text_generated))

In [0]:
print(generate_text(model,"BRUTU",gen_size=500))